<a href="https://colab.research.google.com/github/dayaYanez/MLTSA25_DYanez/blob/main/LAB1_bootcamp_MLTSA_2_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#creating variables and identifying types of variables

my_str = 'hello'


In [3]:
print(my_str)

hello


In [6]:
#creating and integer
my_int = 6

In [7]:
my_float = 6.

In [8]:
print(my_float)

6.0


In [ ]:
my_int * my_float
#it will create a float to storage more

In [ ]:
my_int * my_str

In [ ]:
helloword = "hello" + " word"
#it will concatenate the word into a single str

In [10]:
import numpy as np

In [20]:
my_nparr = np.array([1,2,3])
#make an array of this number
my_nparr

array([1, 2, 3])

In [13]:
my_int * my_nparr

array([ 6, 12, 18])

In [ ]:
my_bool = True
#to create conditions in the code.

In [14]:
my_int = 1

In [ ]:
my_int != 6

In [16]:
if my_int != 6:
  print("my_int is not 6")
else:
  print("int was 6!!")


my_int is not 6


In [41]:
type(my_str)

str

In [21]:
my_nparr.dtype

dtype('int64')

In [22]:
my_nparr.argmax()

2

In [26]:
my_nparr[1:2]

array([2])

In [27]:
#utility function
list(range(1,4))


[1, 2, 3]

In [29]:
for a in range(1,4):
  print(sum(np.arange(0,a)))

0
1
3


In [38]:
#lets create a def

def allodds(lastn):
  """
  lets print odd numbers
  Input:
  lastn:
    lastn: (int) last numberin the list
  Return:
    a list of odd numbers
  """
  odds = []

  for a in range(0, lastn + 1):
    if a % 2==1:
        odds.append(a)
    #print(odds)
  return odds



In [40]:
allodds?

In [39]:
allodds(10)

[1, 3, 5, 7, 9]

In [42]:
#write a def thake a word and check if its a palandrimo, check if its a strain, if not, take it out.

def Palind(palin):
  if palin  type(palin)=="str":
    print("the input is a strain, so we can continue")
    check = palin == palin[::-1]

  else:
    return palin

#TRY IN CLASS ^^^




SyntaxError: invalid syntax (<ipython-input-42-4d700784382d>, line 4)

In [46]:
#SOLUTION

def ispalindome(s):
  "check if a string is a palindome"
  #if  type(s) != str:
    #print("is not a string")

  assert type(s) == str, "input must be a string"
  if s.lowe == s[::-1].lower:   #.lower make anything to lowercases
    return True
  return False



ispalindome("racecar")

True

In [ ]:
# prompt: check if a strain is a palindrom

import numpy as np
#creating variables and identifying types of variables

my_str = 'hello'

print(my_str)
#creating and integer
my_int = 6
my_float = 6.
print(my_float)
#
my_int * my_float
#it will create a float to storage more
my_int * my_str
helloword = "hello" + " word"
#it will concatenate the word into a single str
my_nparr = np.array([1,2,3])
#make an array of this number
my_nparr
my_int * my_nparr
my_bool = True
#to create conditions in the code.
my_int = 1
my_int != 6
if my_int != 6:
  print("my_int is not 6")
else:
  print("int was 6!!")

type(my_str)
my_nparr.dtype
my_nparr.argmax()
my_nparr[1:2]
#utility function
list(range(1,4))

for a in range(1,4):
  print(sum(np.arange(0,a)))
#lets create a def

def allodds(lastn):
  """
  lets print odd numbers
  Input:
  lastn:
    lastn: (int) last numberin the list
  Return:
    a list of odd numbers
  """
  odds = []

  for a in range(0, lastn + 1):
    if a % 2==1:
        odds.append(a)
    #print(odds)
  return odds


allodds?
allodds(10)
#write a def thake a word and check if its a palandrimo, check if its a strain, if not, take it out.

def Palind(palin):
  if isinstance(palin, str):
    palin = palin.lower()  # ignore case
    return palin == palin[::-1] # compare string to reversed string
  else:
    return palin
